{% set name = "openmetadata-managed-apis" %}
{% set version = "1.3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openmetadata_managed_apis-{{ version }}.tar.gz
  sha256: a16139a6338edeb3a5bdd855ef5c9ea51e24bac631bb0c28e84def1ca396f143

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - flask >=1.1.4
    - flask-admin ==1.6.0
    - apache-airflow >=2.2.2
    - pendulum >=2.1.2,<2.2.0

test:
  imports:
    - openmetadata_managed_apis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://open-metadata.org/
  summary: Airflow REST APIs to create and manage DAGS
  dev_url: https://github.com/open-metadata/OpenMetadata
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
