{% set name = "openmetadata-managed-apis" %}
{% set version = "1.0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openmetadata_managed_apis-{{ version }}.tar.gz
  sha256: 2d14ea0f729c759abebfea52906942ec9a7db704d2233668606f8c064d465c64

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - flask-admin ==1.6.0
    - pendulum >=2.1.2,<2.2.0
    - flask >=1.1.4
    - apache-airflow >=2.2.2
    - werkzeug >=1.0,<2.3
    #- rich 13.2.0 has requirement markdown-it-py<3.0.0,>=2.1.0, but you have markdown-it-py 3.0.0.
    - markdown-it-py >=2.1,<3.0.0

test:
  imports:
    - openmetadata_managed_apis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://open-metadata.org/
  summary: Airflow REST APIs to create and manage DAGS
  dev_url: https://github.com/open-metadata/OpenMetadata
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
