{% set name = "openmetadata-managed-apis" %}
{% set version = "1.8.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openmetadata_managed_apis-{{ version }}.tar.gz
  sha256: e458c613e0964f158dc154572fb9d968da619acf6d5e26e2af9597894005224c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=70.3.0
    - pip
  run:
    - python >={{ python_min }}
    - pendulum >=3.0,<4.dev0
    - apache-airflow >=2.2.2
    - flask ==2.2.5
    - flask-admin ==1.6.0
    - apache-airflow-core >=3.0.2,<3.1.0

test:
  imports:
    - openmetadata_managed_apis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://open-metadata.org/
  summary: Airflow REST APIs to create and manage DAGS
  dev_url: https://github.com/open-metadata/OpenMetadata
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
