{% set name = "openmetadata-managed-apis" %}
{% set version = "0.13.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openmetadata_managed_apis-{{ version }}.tar.gz
  sha256: 7c5dabdf0cced1b30ef827743a93641226360034735f5e1876430e1ac92e702f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - apache-airflow >=2.2.2
    - flask >=1.1.4
    - pendulum >=2.1.2
    - flask-admin ==1.6.0

test:
  imports:
    - openmetadata_managed_apis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://open-metadata.org/
  summary: Airflow REST APIs to create and manage DAGS
  dev_url: https://github.com/open-metadata/OpenMetadata
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
