{% set name = "openmetadata-managed-apis" %}
{% set version = "1.5.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openmetadata_managed_apis-{{ version }}.tar.gz
  sha256: 1b36696352d16caaf1848e939828ae6bfa98b8777cef89c0c56de2ae744ec2ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=70.3.0
    - pip
  run:
    - python >=3.8
    - pendulum >=3.0,<4.dev0
    - apache-airflow >=2.2.2
    - flask ==2.2.5
    - flask-admin ==1.6.0

test:
  imports:
    - openmetadata_managed_apis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://open-metadata.org/
  summary: Airflow REST APIs to create and manage DAGS
  dev_url: https://github.com/open-metadata/OpenMetadata
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
